name: server
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  sqlite3: ^2.9.0
  sqflite: ^2.4.2
  path: ^1.9.1
  uuid: ^4.5.1


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
